### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by mklabs** [Awesome-Windows/Awesome#1]
Hi!

Nice initiative. Thank you for putting this together.

I started working on windows 10 a bit more for day to day development and I really love it.

Here are some of the tools I highly suggest adding to the list, they helped me lot getting a reasonably looking shell:

- https://github.com/lukesampson/concfg
- https://github.com/lukesampson/psutils
- https://github.com/lukesampson/pshazz

or everything @lukesampson has been doing really. scoop is already on the list :+1: 

And some random notes / projects

- https://github.com/mklabs/dotfiles/tree/master/i3#windows-10-note
- https://www.npmjs.com/package/hyperfish

I would be happy to help, in any way I can. I'll init a PR for each individual suggestions I might have, but thought it would be good to say hi.

Thanks!

**Comment by rahulkapoor90** [comment]
@mklabs Hi! your suggestions are really good. please send a pull request so that we can accept it but remember to follow the contribution rules given.

**Comment by mklabs** [comment]
Will do :)

**Comment by mklabs** [comment]
@rahulkapoor90 Something quite awesome would be an [i3](https://github.com/mklabs/todo/issues/13) for windows 10. i3's really awesome, I'm really missing it and would use an i3 clone on either windows or osx. Tiling window managers are nice. even more on hdpi/retina displays.

cc @lukesampson

**Comment by rahulkapoor90** [comment]
i am having difficulty understanding about i3. can you explain what exactly i3 is?
