### ISSUE TITLE
Question about NitroPDF

### ISSUE THREAD

**Issue by ChengjunJia** [Awesome-Windows/Awesome#107]
I tried to use the Nitro PDF to review PDF files( the other software--Sumatra PDF does not support the function), but the program can not work and I think I have installed it correctly......
Maybe the reason is that I use Win10? I am not sure and I have not figured out the real reason.
Besides, I recommend the jisupdf: http://www.jisupdf.com/.

**Comment by rahulkapoor90** [comment]
Nitro PDF works perfectly for me. Maybe you need a reinstallation. I'll try your recommendation as well.
