### ISSUE TITLE
Is there any good Image Viewer app replacement for Windows?

### ISSUE THREAD

**Issue by doggy8088** [Awesome-Windows/Awesome#109]
Is there any good Image Viewer app replacement for Windows?  I couldn't find it on the list.

**Comment by pwab** [comment]
I am using _nomacs_ ( https://nomacs.org/ ).
It's fast, easy to use, has batch support (for conversion or something like that) and there are a few plugins. I think it is still maintained - but I'm not sure. Latest version was released March 2017.

Depending on your needs you can also search for alternatives here: https://alternativeto.net/software/microsoft-photos/?platform=windows

**Comment by rahulkapoor90** [comment]
There are replacements and I did try most of them but trust me they are not as close to windows 10 one. The photos app will see good updates in future and it currently has a lot of features that are worth keeping.

**Comment by R3DJOK3R1** [comment]
Ifranviewer
