### ISSUE TITLE
Suggestion about screenshot

### ISSUE THREAD

**Issue by ChengjunJia** [Awesome-Windows/Awesome#135]
I recommend snipaste
https://www.snipaste.com/

**Comment by Pokerpoke** [comment]
+1
This app is awesome~~~

**Comment by R3DJOK3R1** [comment]
Greenshot

**Comment by DaDaDaimaou** [comment]
XShare
https://getsharex.com

**Comment by rahulkapoor90** [comment]
sharex is the one that's highly recommended and updated frequently with bug fixes etc.
