### ISSUE TITLE
[Utilities]YYNote：Cross platform todolist that can be embedded on the desktop

### ISSUE THREAD

**Issue by cg200776** [Awesome-Windows/Awesome#153]
Cross platform todolist that can be embedded on the desktop

For windows：www.6fcsj.com

For ios:https://itunes.apple.com/cn/app/id1175974945?mt=8

For andiord：https://play.google.com/store/apps/details?id=com.xiaohuangtiao

**Comment by rahulkapoor90** [comment]
Already have to-do apps listed.
