### ISSUE TITLE
Just a few comments and suggestions

### ISSUE THREAD

**Issue by egeerardyn** [Awesome-Windows/Awesome#2]
Here are just some errors I found (and some suggestions). Feel free to carry out those you like and disregard the others, I'm just a bit too lazy to make a decent pull request (sorry).

 - [x] Replace `[Textual 5](http://www.mirc.com)` with `[mIRC](http://www.mirc.com)`
 - [x] Replace `## Editors` with `## Text Editors` (also in table of contents)
 - [x] Unless you actively use `Profanity` and `WeeChat` (CLI IRC clients) on Windows, I would remove them because they are not really typical Windows tools (they do work, I guess, but I think only very few Windows users like the CLI)
 - [x] Fix the typo in `[ListEry](http://www.listAry.com)` (should both be "a")
 - [x] I would put `MTPutty`, `Putty` and `MobaXterm` under "terminal" rather than "developer"
 - [x] Add [`[Sysinternals Suite](https://technet.microsoft.com/en-us/sysinternals/bb842062) - Tool suite by Mark Russinovich that provides access to Windows internals for troubleshooting: processes, physical ports, disk activity, ...`](https://technet.microsoft.com/en-us/sysinternals/bb842062)
 - [x] The "other" category is still empty.

For what it's worth, this is what I typically install on a new Windows box (using Chocolatey):
```
choco install adwcleaner
choco install malwarebytes
choco install spybot
choco install ccleanerd
choco install unchecky

choco install ChocolateyGUI
choco install notepadplusplus
choco install windirstat
choco install teamviewer

choco install GoogleChrome-AllUsers
choco install adblockpluschrome
choco install flashplayerplugin
choco install adblockplusie
choco install adblockplusfirefox
choco install lastpass

choco install vlc
choco install 7zip
choco install adobereader
choco install libreoffice

choco install Skype
choco install spotify
choco install evernote
choco install dropbox
choco install googledrive

choco install paint.net
choco install inkscape
choco install gimp
choco install picasa

choco install filezilla
choco install autohotkey
choco install daemontools
choco install wireshark
choco install sysinternals

choco install git
choco install cyg-get
choco install ConEmu
```
There are quite some duplicates with your list but maybe there are some things you guys like as well (FYI: I don't claim that everything on here is awesome, some things "just work" (e.g. Skype and Spotify)):

**Comment by rahulkapoor90** [comment]
Done. I have added most of the things you suggested. i'll add more soon. thanks!
