### ISSUE TITLE
Alacritty is actually supporting Windows now

### ISSUE THREAD

**Issue by Z-Shang** [Awesome-Windows/Awesome#236]
![image](https://user-images.githubusercontent.com/859939/56109769-586fd280-5f95-11e9-9f2b-001be701def4.png)

It can be installed via `choco`.

The conpty backend is still experimental (usable, just the cursor will be flashing at the left top corner). Its winpty is totally usable.

**Comment by rahulkapoor90** [comment]
Thanks, please add a PR otherwise I'll add soon.
