### ISSUE TITLE
Add GoldenDict

### ISSUE THREAD

**Issue by gamtiq** [Awesome-Windows/Awesome#253]
http://goldendict.org/
It is a good dictionary lookup application.

**Comment by HappyDoggo** [comment]
Nice suggestion! Please create a pull request. See [Contribution Guidelines.](https://github.com/Awesome-Windows/Awesome/blob/master/Contributing.md)

**Comment by gamtiq** [comment]
Into which category should GoldenDict be added: into new category Dictionaries or some existent category?

**Comment by HappyDoggo** [comment]
WordWeb (another dictionary) is listed under Productivity.

**Comment by hoodiearon** [comment]
:tada:
