### ISSUE TITLE
[Ownership transfer] Is this project still alive?

### ISSUE THREAD

**Issue by fdrobidoux** [Awesome-Windows/Awesome#271]
There hasn't been an update in 3 months and there are still 25 pull requests waiting for many months.

If whoever maintains this repo doesn't have the time nor energy to look over this repo, it might be time to transfer ownership of the repo to someone who's got time to manage it.

**Comment by vinz243** [comment]
You can contact him here : https://github.com/rahulkapoor90

**Comment by rahulkapoor90** [comment]
Hi There, the project is still alive, I'm working on some major updates here, stay tuned. 👍
