### ISSUE TITLE
Add ExifTool

### ISSUE THREAD

**Issue by JNavas2** [Awesome-Windows/Awesome#301]
[ExifTool by Phil Harvey](https://exiftool.org/)
ExifTool is a platform-independent toolset for reading, writing and editing meta information in a wide variety of file types, as well as the maker notes of many digital cameras.

**Comment by rahulkapoor90** [comment]
Thanks for the recommendation, if you would like it to be added to the list, please create an Pull Request Instead. Thanks for Understanding!

**Comment by JNavas2** [comment]
Thanks for the suggestion, but:
- It's your list, not mine.
- I'm not currently setup to do GitHub Pull Requests, which is _too much hassle_ just for this.
- Since you've not that interested in adding it, I'll just write it off as a waste of my time.

**Comment by rahulkapoor90** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by JNavas2** [comment]
As I said, that's _too much hassle_.
