### ISSUE TITLE
Add Media Player Classic Home Cinema

### ISSUE THREAD

**Issue by JNavas2** [Awesome-Windows/Awesome#305]
[Media Player Classic Home Cinema](https://sourceforge.net/projects/mpc-hc/)
An extremely light-weight, open source media player for Windows supporting all common video and audio file formats.

**Comment by rahulkapoor90** [comment]
Thanks for the recommendation, if you would like it to be added to the list, please create an Pull Request Instead. Thanks for Understanding!

**Comment by JNavas2** [comment]
Thanks for the suggestion, but:
- It's your list, not mine.
- I'm not currently setup to do GitHub Pull Requests, which is _too much hassle_ just for this.
- Since you've not that interested in adding it, I'll just write it off as a waste of my time.

**Comment by rahulkapoor90** [comment]
This suggestion wouldn't be added, anyways. There are better players than the Media Player Classic Home Cinema. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by JNavas2** [comment]
1. With respect, I disagree. VLC, for example, has known longstanding bugs.
2. As I said, that's _too much hassle_.

**Comment by rahulkapoor90** [comment]
1. ok.
2. ok.
