### ISSUE TITLE
Add MediaInfo

### ISSUE THREAD

**Issue by JNavas2** [Awesome-Windows/Awesome#306]
[MediaInfo](https://mediaarea.net/en/MediaInfo)
Convenient unified display of the most relevant technical and tag data for video and audio files.

**Comment by rahulkapoor90** [comment]
Thanks for the recommendation, if you would like it to be added to the list, please create an Pull Request Instead. Thanks for Understanding!

**Comment by JNavas2** [comment]
Thanks for the suggestion, but:
- It's your list, not mine.
- I'm not currently setup to do GitHub Pull Requests, which is _too much hassle_ just for this.
- Since you've not that interested in adding it, I'll just write it off as a waste of my time.

**Comment by rahulkapoor90** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by JNavas2** [comment]
As I said, that's _too much hassle_.
