### ISSUE TITLE
Windows' logo instead of Micosoft's

### ISSUE THREAD

**Issue by Emeryao** [Awesome-Windows/Awesome#315]
Sorry to be picky  
but the [current logo image](https://github.com/Awesome-Windows/Awesome/blob/master/media/main-awesomeWindows.png) on top of README.md is the logo of Microsoft  
and Windows has its own one like this  
![image](https://user-images.githubusercontent.com/3591899/75096014-ef55e400-55d5-11ea-9fcf-fe9a0e5d1cfe.png)

**Comment by LooTKinGz** [comment]
Windows

**Comment by rahulkapoor90** [comment]
Hey, I've thought about designing one like this as well but couldn't find the solution. if you can help me find one would be great! :)
