### ISSUE TITLE
[FEATURE REQUEST] Multi-client chat software

### ISSUE THREAD

**Issue by Dr-Flay** [Awesome-Windows/Awesome#325]
I see you don't list any of the available multi-client options for chat.

Personally I use Trillian most as it is also available for android, but in the Windows world we basically are left with 3 options, which I will list in order of ease of use.
**Trillian**, supports FB, Google, Jabber, IRC, Twitter and a couple more networks inc. its own network Astra which is Open Source.
Trillian can sync across devices.
https://trillian.im/help/user/#third-party-integrations
**Pidgin** (Windows and Linux), Open Source and supports a huge list of networks and plugins
https://www.pidgin.im/plugins/?publisher=all&query=&type=Protocol
**Miranda-NG** (Windows only) Open Source and also supports a huge list of networks and plugins
https://wiki.miranda-ng.org/index.php?title=Category:Protocols/en

The main advantages of tools like this are a single consolidated experience across multiple chat networks, a whole lot less RAM and resource use, not caring when another chat network fades away, but perhaps most usefully, to be able to link the contact info for an individual on multiple networks into a single meta-contact.
All 3 are free but Trillian has a few limits unless you pay, such as not syncing offline messages across devices.

**Comment by rahulkapoor90** [comment]
Thanks for recommending! I'm adding Trillian and Pidgin after careful review. :)
