### ISSUE TITLE
推荐 HBuilderX

### ISSUE THREAD

**Issue by ruxia-TJY** [Awesome-Windows/Awesome#331]
没发现这个软件。推荐一下：HBuilderX

网址：https://www.dcloud.io/hbuilderx.html

**Comment by hoochanlon** [comment]
有意思 :)

**Comment by hoochanlon** [comment]
不错。既然推荐这款软件，那么它在同类的IDE中，应该有着易用&便捷性相关等出众的优点:)

**Comment by ruxia-TJY** [comment]
> 不错。既然推荐这款软件，那么它在同类的IDE中，应该有着易用&便捷性相关等出众的优点:)

emm，打动我的就是打开很快，每次我打开vscode

**Comment by ruxia-TJY** [comment]
> 不错。既然推荐这款软件，那么它在同类的IDE中，应该有着易用&便捷性相关等出众的优点:)

HX打开很快，vscode总是很慢，这是感觉最好的一点，而且对新手很友好，因为环境可以直接用
emm，其实对我最重要的就是比vscode打开快(笑哭)
