### ISSUE TITLE
Redundant entries in Chat Clients

### ISSUE THREAD

**Issue by robbirob** [Awesome-Windows/Awesome#337]
Some apps are listed twice.

![image](https://user-images.githubusercontent.com/466034/83296966-fc482c00-a1f1-11ea-9f83-7eb1f406f50f.png)

Regards,
Robert

**Comment by robbirob** [comment]
Created a PR #338

**Comment by rahulkapoor90** [comment]
Hi, this could've been an merge issue recently. Thanks I've merged your previous PR.
