### ISSUE TITLE
there seem to be two "ShareX"'s

### ISSUE THREAD

**Issue by Kqzz** [Awesome-Windows/Awesome#347]
![image](https://user-images.githubusercontent.com/48300938/85789127-0a5b7080-b6fc-11ea-945e-a438522a6c9b.png)

**Comment by fraidnk** [comment]
And also two "SpeedCrunch"es

**Comment by hkrtrainingshyderabad** [comment]
There are two "ShareX"s. One is an anti-spam, community and file sharing tool designed for users that want to share files with friends or family on any device that has internet access. The other is meant for larger organizations to provide cloud based File Sharing for employees who need secure file sharing in the office or remotely. [golang training](https://hkrtrainings.com/golang-training)
