### ISSUE TITLE
[FEATURE REQUEST] qttabbar and windowtop

### ISSUE THREAD

**Issue by cathaysia** [Awesome-Windows/Awesome#384]
- WindowTop: https://github.com/gileli121/WindowTop. Let your program window keeps at top, dark mode, blur, etc.
- QtTabBar: http://qttabbar.wikidot.com/. Let your explore has a tab bar. I thinks it's beta than clover.

**Comment by hkrtrainingshyderabad** [comment]
If you love the look and feel of wood but don't have the space to fully furnish your home, then qttabbar and windowtop are perfect for you! The collection features a simple design that allows you to add some character without taking up too much space, while still providing stylish furniture in your room. [Oracle Fusion HCM Online Training](https://hkrtrainings.com/oracle-fusion-hcm-training)
