### ISSUE TITLE
Applications missing "open source" image

### ISSUE THREAD

**Issue by Keith94** [Awesome-Windows/Awesome#42]
Please add the open source image beside their names.

* VLC: http://www.videolan.org/vlc/download-sources.html
* 7-Zip: https://sourceforge.net/projects/sevenzip/
* PeaZip: https://sourceforge.net/projects/peazip/
* SumatraPDF: https://github.com/sumatrapdfreader/sumatrapdf
* Thunderbird: http://ftp.mozilla.org/pub/thunderbird/releases/

**Comment by rahulkapoor90** [comment]
Sure. If you can send a pull request then that would be great.
