### ISSUE TITLE
Similar Repo

### ISSUE THREAD

**Issue by EMLVIRUS** [Awesome-Windows/Awesome#45]
Inspired by this repo, I create [Amazing Windows Apps](https://github.com/EMLVIRUS/Amazing-Windows-Apps) that sync with gitbook.
Please do take a glance and tell me how you require me or maybe we could combine.
For further discussion, drop me an [email](mailto:EMLVIRUS@outlook.com)

**Comment by rahulkapoor90** [comment]
Hi. thanks for creating this issue. yes, we can combine! how shall we proceed?
