### ISSUE TITLE
Icon placement

### ISSUE THREAD

**Issue by Jogai** [Awesome-Windows/Awesome#5]
The icons don't stand out at the end of a line. Maybe move them to the beginning and use empty ones for the entries where they aren't applicable. (Well, the latter part is maybe hindering contributions, so this needs a little thought).

Also, wouldn't it be safer to maintain the icons in this repo?

**Comment by rahulkapoor90** [comment]
I'll maintain the icons in this repo soon but i don't understand the "empty ones" part, can you explain a little more about it?

**Comment by rahulkapoor90** [comment]
@Jogai I have started to maintain the icons in this repo, thank you!

**Comment by Jogai** [comment]
I was thinking about moving the icons to the start of the entries. That way they would be easier to spot and all lined up, but for that to work you need empty ones to indent the entries without icons.

**Comment by rahulkapoor90** [comment]
@Jogai can you send a pull request?
